name: test-foreman

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]

jobs:

  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: run unit tests
      run: go test ./*.go 

    - name: run integration tests
      run: ./test.sh
